obj-$(CONFIG_RISCV_KPROBES_KUNIT) += kprobes_riscv_kunit.o
obj-$(CONFIG_RISCV_KPROBES_SIMULATE_KUNIT) += kprobes_simulate_riscv_kunit.o

kprobes_riscv_kunit-objs := test-kprobes.o test-kprobes-asm.o
kprobes_simulate_riscv_kunit-objs := test-kprobes-simulate.o
